blue_threshold : 10
blue_h_min : 80
blue_s_min : 80
blue_v_min :  0
blue_h_max : 115
blue_s_max : 127
blue_v_max :  200
red_threshold : 10
red_h_min : 0
red_s_min : 0
red_v_min : 76
red_h_max : 35
red_s_max : 127
red_v_max : 200