blue_threshold : 10
blue_h_min : 30
blue_s_min : 90
blue_v_min :  30
blue_h_max : 90
blue_s_max : 200
blue_v_max :  150

red_threshold : 10
red_h_min : 0
red_s_min : 45
red_v_min : 80
red_h_max : 6
red_s_max : 255
red_v_max : 255